version: '2'

issues:
  max-same-issues: 50

linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    - copyloopvar
    - cyclop
    - dupl
    - durationcheck
    - errcheck
    - errname
    - errorlint
    - exhaustive
    - exptostd
    - fatcontext
    - funlen
    - gocheckcompilerdirectives
    - gochecksumtype
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - gomoddirectives
    - gosec
    - govet
    - ifaceassert
    - ineffassign
    - intrange
    - loggercheck
    - makezero
    - mirror
    - musttag
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    - perfsprint
    - predeclared
    - promlinter
    - protogetter
    - reassign
    - rowserrcheck
    - sloglint
    - spancheck
    - sqlclosecheck
    - staticcheck
    - testableexamples
    - testifylint
    - testpackage
    - tparallel
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - usetesting
    - wastedassign
    - whitespace
    - exhaustruct

  settings:
    cyclop:
      max-complexity: 30
      package-average: 10.0

    errcheck:
      check-type-assertions: true
      exclude-functions:
        - (io.Closer).Close
        - (*os.File).Close

    exhaustive:
      check:
        - switch
        - map
      default-signifies-exhaustive: true

    exhaustruct:
      exclude:
        - ^net/http\.
        - ^net/url\.
        - ^os/exec\.
        - ^reflect\.
        - ^github\.com/go-git/
        - Token$
        - Statement$
        - Expression$
        - Literal$
        - Type$
        - Object$
        - Hash$
        - Environment$
        - Parser$
        - Lexer$
        - Builder$

    funcorder:
      struct-method: false

    funlen:
      lines: 200
      statements: 80

    gocognit:
      min-complexity: 30

    gocritic:
      enabled-tags:
        - diagnostic
        - style
        - performance
      disabled-checks:
        - ifElseChain
        - exitAfterDefer
        - nestingReduce

    gosec:
      excludes:
        - G304 # File inclusion
        - G306 # File permissions
        - G301 # Directory permissions
        - G302 # File permissions
        - G404 # Weak random (math/rand/v2 is fine)
        - G114 # HTTP timeouts
        - G115 # Integer conversions

    govet:
      enable-all: true
      disable:
        - fieldalignment
        - shadow

    nakedret:
      max-func-lines: 0

    nolintlint:
      allow-no-explanation:
        - funlen
        - gocognit
        - golines
        - gochecknoglobals
        - reassign
      require-explanation: true
      require-specific: true

    perfsprint:
      strconcat: false
      err-error: false

    staticcheck:
      checks:
        - all
        - -ST1000
        - -ST1003
        - -ST1005 # Error capitalization
        - -ST1016

    unused:
      field-writes-are-uses: true

  exclusions:
    rules:
      - text: 'should have a package comment'
        linters:
          - revive
      - text: 'exported \S+ \S+ should have comment( \(or a comment on this block\))? or be unexported'
        linters:
          - revive
      - text: 'package comment should be of the form ".+"'
        linters:
          - revive
      - text: 'comment on exported \S+ \S+ should be of the form ".+"'
        linters:
          - revive
          - staticcheck
      - path: '_test\.go'
        linters:
          - bodyclose
          - dupl
          - errcheck
          - funlen
          - goconst
          - gosec
          - noctx
          - wrapcheck
          - gochecknoglobals
          - exhaustruct
          - cyclop
          - gocognit