// Code generated by "stringer -type=ErrorCode"; DO NOT EDIT.

package errors

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SyntaxError-0]
	_ = x[TypeError-1]
	_ = x[TypeMismatchError-2]
	_ = x[UndefinedVariableError-3]
	_ = x[DivisionByZeroError-4]
	_ = x[ConstantReassignmentError-5]
	_ = x[RuntimeError-6]
	_ = x[IndexNotSupportedError-7]
	_ = x[IndexOutOfBoundsError-8]
	_ = x[KeyError-9]
	_ = x[ImportError-10]
	_ = x[VariableReassignmentError-11]
	_ = x[NotCallableError-12]
	_ = x[InvalidAssignmentError-13]
	_ = x[ArgumentError-14]
	_ = x[ParseError-15]
	_ = x[PropertyAccessOnNonObjectError-16]
	_ = x[UnknownOperatorError-17]
	_ = x[FeatureNotImplementedError-18]
}

const _ErrorCode_name = "SyntaxErrorTypeErrorTypeMismatchErrorUndefinedVariableErrorDivisionByZeroErrorConstantReassignmentErrorRuntimeErrorIndexNotSupportedErrorIndexOutOfBoundsErrorKeyErrorImportErrorVariableReassignmentErrorNotCallableErrorInvalidAssignmentErrorArgumentErrorParseErrorPropertyAccessOnNonObjectErrorUnknownOperatorErrorFeatureNotImplementedError"

var _ErrorCode_index = [...]uint16{0, 11, 20, 37, 59, 78, 103, 115, 137, 158, 166, 177, 202, 218, 240, 253, 263, 293, 313, 339}

func (i ErrorCode) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_ErrorCode_index)-1 {
		return "ErrorCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ErrorCode_name[_ErrorCode_index[idx]:_ErrorCode_index[idx+1]]
}
